version: '3.9'
services:
  docker:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["sleep","infinity"]
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "40000:40000"
volumes:
  jenkins_home: