version: '3.9'
services:
  dnd:
    image: dnd:v1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["sleep","infinity"]
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "40000:50000"
  node:
    build: .
    ports: 
      - 3000:3001
    command: ["sleep","infinity"]
volumes:
  jenkins_home: