version: '3.9'
services:
  node:
    image: node:17
    ports:
      - "80:80"
    command: ['sleep','infinity']
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "40000:40000"
volumes:
  jenkins_home: