on:
  push:
    branches: [ main ]
    
name: Build and deploy

env:
  PROJECT_ID: test-k8s-j1
  GAR_LOCATION: asia-southeast1-c # TODO: update region of the Artifact Registry
  GKE_CLUSTER: cluster-jeep-1    # TODO: update to cluster name
  GKE_ZONE: asia-southeast1-c   # TODO: update to cluster zone
  REPOSITORY: jeepajeep/storefront # TODO: update to Artifact Registry docker repository
  IMAGE: jeepajeep/storefront
  
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jeepajeep/storefront:${GITHUB_REF##*/}
      
    - name: login
      run: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      env:
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: push Docker image
      run: docker push jeepajeep/storefront:${GITHUB_REF##*/}
 
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
    
    - name: test get pod
      run: kubectl get pod
      
    - name: test deploy
      run: kubectl rollout restart deployment deployment-store

      
    - name: test get pod again
      run: kubectl get pod
